### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by roshanjonah** [pprevos/thirdhemisphere-theme#1]
Great project! Do you have rough guidelines on creating new pages, blog posts, and so on? I know it's not production-ready but it would be good to dig right in and see where we can improve and help with this project.

**Comment by pprevos** [comment]
Hi Roshan, I am starting to use it in production and hope to complete a properly deployed version with instructions next  week.

This is the template in action: https://horizonofreason.com/

Any assistance is appreciated. Did you have anything in mind?

I am adding admin pages to help creating a .htaccess file instead of html-redirects and an overview of all pages.

**Comment by roshanjonah** [comment]
Looks great! Well done! Is that using the code here in this repo?

What attracted me to the project is the SEO optimization so will see if I can contribute in that area or in features once you push the latest code through next week. Cheers

**Comment by roshanjonah** [comment]
Btw just noticed this so well done! Really good stuff :) 

<img width="740" alt="screenshot_158" src="https://user-images.githubusercontent.com/20136098/87204050-ffd5e380-c357-11ea-8b0a-7c07f2d473cd.png">

**Comment by pprevos** [comment]
Thanks roshanjonah , 

I have completed the theme and it is now in production on four of my websites. The GitHub page is updated and I have completed the documentation for all features so far. There are many links to SEO websites that explain the theory of what I implemented.

I would love some help with the UI to make it look a bit smoother. See the action list on the bottom of the Readme.

Peter

**Comment by roshanjonah** [comment]
Peter,

Unfortunately, I ended up building it on the Amperage theme for Hugo which was also great with SEO side of things and had to make some adjustments to make it more efficient. Your work looks excellent. I will look into it once I find a bit of time. and see the ways I can help.

Cheers!
RJ

**Comment by pprevos** [comment]
Thanks, RJ.
